name: Laravel Dusk

on:
  push:
    branches: [ 2.0 ]
  pull_request:
    branches: [ 2.0 ]

jobs:
  dusk:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - laravel: '9.*'
            php: '8.1'
          - laravel: '10.*'
            php: '8.2'
          - laravel: '11.*'
            php: '8.3'
          - laravel: '12.*'
            php: '8.3'
          - laravel: '13.*'
            php: '8.4'

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 5.7
          mysql root password: 123456
          mysql database: laravel
          mysql user: root
          mysql password: 123456

      - name: Install Dependencies
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-tests ${{ matrix.laravel }}
          sh ./tests/bin/install-dep.sh

      - name: Install Admin
        run: sh ./tests/bin/install-admin.sh

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Start Server
        run: sh ./tests/bin/start.sh

      - name: Run test suite
        run: cd ./laravel-tests && php artisan dusk
